runs:
  using: "composite"
  steps:
    - run: sudo systemctl start postgresql.service
      shell: bash
    - run: sudo -u postgres createuser --createdb --superuser ${USER}
      shell: bash
    - run: createdb ${USER}
      shell: bash
    - run: echo "::set-env name=POSTGRES_URL::postgres:///${{ env.USER }}"
      shell: bash
