name: "Postgres"
description: "Start PostgreSQL in the GitHub Actions VM"
runs:
  using: "composite"
  steps:
    - run: sudo sed -i s/scram-sha-256/trust/g /etc/postgresql/*/main/pg_hba.conf
      shell: bash

    - run: sudo systemctl start postgresql.service
      shell: bash

    - run: sudo -u postgres createuser --createdb --superuser ${USER}
      shell: bash

    - run: createdb ${USER}
      shell: bash

    - run: echo "POSTGRES_URL=postgres://localhost/${USER}" >> $GITHUB_ENV
      shell: bash
