name: Test this action
on:
  pull_request:
  push:
    branches-ignore:
    - v1
    paths-ignore:
    - README.md
  schedule:
    - cron:  "0 6 * * 6" # 06:00 every Saturday
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04 ]

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - run: psql --version
    - uses: ./
    - run: pg_isready --dbname=$POSTGRES_URL
    - run: psql --command='CREATE TABLE tbl()' $POSTGRES_URL
    - run: psql --command='\d' $POSTGRES_URL
    - run: psql --command='SELECT * FROM pg_available_extensions' $POSTGRES_URL
